In [1]:
from tensorflow.keras.preprocessing.text import one_hot

c:\users\chanc\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]


In [4]:
voc_size=10000

In [5]:
rep=[one_hot(words,voc_size)for words in sent]

In [6]:
rep

[[9478, 2423, 7601, 8402],
 [9478, 2423, 7601, 179],
 [9478, 789, 7601, 1102],
 [7743, 2163, 7424, 6540, 1164],
 [7743, 2163, 7424, 6540, 9236],
 [9068, 9478, 8975, 7601, 6368],
 [6599, 7633, 9266, 6540]]

# word embedding representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [9]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9478 2423 7601 8402]
 [   0    0    0    0 9478 2423 7601  179]
 [   0    0    0    0 9478  789 7601 1102]
 [   0    0    0 7743 2163 7424 6540 1164]
 [   0    0    0 7743 2163 7424 6540 9236]
 [   0    0    0 9068 9478 8975 7601 6368]
 [   0    0    0    0 6599 7633 9266 6540]]


In [12]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 1s 582ms/step
[[[-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362
   -0.01609988 -0.0277351  -0.03569959 -0.01186191  0.03064317]
  [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362
   -0.01609988 -0.0277351  -0.03569959 -0.01186191  0.03064317]
  [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362
   -0.01609988 -0.0277351  -0.03569959 -0.01186191  0.03064317]
  [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362
   -0.01609988 -0.0277351  -0.03569959 -0.01186191  0.03064317]
  [ 0.0234648   0.04771627  0.02594179  0.03668055  0.01062888
   -0.03141098  0.00681534  0.00730139 -0.02848579  0.00151179]
  [-0.02361653 -0.03193849  0.04384561  0.01787077  0.0007147
    0.04348833 -0.00228369 -0.0087526  -0.0372303   0.03040501]
  [ 0.0312485  -0.02575704 -0.01253343  0.02229417  0.00157789
   -0.03189687  0.03492336  0.02458872  0.03174652  0.00993846]
  [-0.01082357  0.03709951 -0.04188437  0.02898843  0.04923

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 9478, 2423, 7601, 8402])

In [18]:

print(model.predict(embedded_docs)[0])


1/1 [==============================] - 0s 64ms/step
[[-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362 -0.01609988
  -0.0277351  -0.03569959 -0.01186191  0.03064317]
 [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362 -0.01609988
  -0.0277351  -0.03569959 -0.01186191  0.03064317]
 [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362 -0.01609988
  -0.0277351  -0.03569959 -0.01186191  0.03064317]
 [-0.01565318 -0.0225289   0.00922276  0.00249268 -0.02890362 -0.01609988
  -0.0277351  -0.03569959 -0.01186191  0.03064317]
 [ 0.0234648   0.04771627  0.02594179  0.03668055  0.01062888 -0.03141098
   0.00681534  0.00730139 -0.02848579  0.00151179]
 [-0.02361653 -0.03193849  0.04384561  0.01787077  0.0007147   0.04348833
  -0.00228369 -0.0087526  -0.0372303   0.03040501]
 [ 0.0312485  -0.02575704 -0.01253343  0.02229417  0.00157789 -0.03189687
   0.03492336  0.02458872  0.03174652  0.00993846]
 [-0.01082357  0.03709951 -0.04188437  0.02898843  0.0492362   0.04586479